services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # Puerto de la API S3
      - "9001:9001" # Puerto de la consola web
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Este contenedor temporal configura MinIO y crea el bucket automáticamente
  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set myminio http://minio:9000 admin password123;
      mc mb myminio/usuarios-bucket;
      mc anonymous set public myminio/usuarios-bucket;
      exit 0;
      "

volumes:
  minio_data: